### ISSUE TITLE
Installation error about digenome-toolkit2

### ISSUE THREAD

**Issue by panxiaoguang** [chizksh/chizksh#2]
Hello, I have some installation problems about digenome-toolkit2, I can compile bamtools successfully, but when I finally compile and install find_position_bam.cpp, I get an error that shows missing some header files under the api path, I confirm that I have followed the instructions exactly, but I still have these problems because that repository does not have an open issue, so leave a comment under your blog!
error like this 
```
1.find_position_bam.cpp:7:27: error: api/BamReader.h: No such file or directory
1.find_position_bam.cpp:10: error: ‘BamTools’ is not a namespace-name
1.find_position_bam.cpp:10: error: expected namespace-name before ‘;’ token
1.find_position_bam.cpp: In function ‘void usage()’:
1.find_position_bam.cpp:13: error: ‘cout’ was not declared in this scope
1.find_position_bam.cpp:13: error: ‘endl’ was not declared in this scope
1.find_position_bam.cpp:15: error: ‘exit’ was not declared in this scope
1.find_position_bam.cpp: In function ‘int main(int, char**)’:
1.find_position_bam.cpp:42: error: ‘BamReader’ was not declared in this scope
1.find_position_bam.cpp:42: error: expected ‘;’ before ‘reader’
1.find_position_bam.cpp:50: error: ‘reader’ was not declared in this scope
```

**Comment by chizksh** [comment]
Thanks for letting me know, actually it could happens when you are running "build_find_position_bam.sh"
Could you run this and let me know how it works?

`g++ -O3 1.find_position_bam.cpp -o 1.find_position_bam -Ibamtools/src -Lbamtools/lib -lbamtools -lz`

**Comment by panxiaoguang** [comment]
> Thanks for letting me know, actually it can happen when you are running "build_find_position_bam.sh"
> Could you run this and let me know how it works?
> 
> `g++ -O3 1.find_position_bam.cpp -o 1.find_position_bam -Ibamtools/src -Lbamtools/lib -lbamtools -lz`

Yes, when I run the command alone, the same error is reported, when bamtools compiles, the include and lib folders are not found, so the error of not finding the header is reported, because I compiled and installed the software as a user on a cluster with no root privileges, is this the reason why I cannot find the link library or header file? So how do I change this code to complete the compilation

**Comment by chizksh** [comment]
> the include and lib folders are not found

It seems that you are still having some issues with `build_find_position_bam.sh`

First, you can try older version of bamtools like below:
```bash
wget https://github.com/pezmaster31/bamtools/archive/v2.4.0.zip`
unzip v2.4.0.zip -d ./bamtools
mkdir bamtools_build
cd bamtools_build
cmake ../bamtools
make
cd ..
g++ -O3 1.find_position_bam.cpp -o 1.find_position_bam -Ibamtools/include -Lbamtools/lib -lbamtools -lz
#or
g++ -O3 1.find_position_bam.cpp -o 1.find_position_bam -Ibamtools/src -Lbamtools/lib -lbamtools -lz
 
```

Second, it could also happen if the cluster does not have `make` and `cmake` or has older versions. 
This looks like a compiling error and does not reproduce in my cases, but at least I would say 1) you can ask your server admin to update `cmake` or `make`, 2) you can use `singularity` or `conda` to install/update `cmake` or `make` without root privileges.

Those are examples of successful compiling processes:
```bash
cmake ../bamtools                                                            
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
...
-- Generating done
-- Build files have been written to: /XXX/digenome-toolkit2/bamtools_build
```

```bash
make
Scanning dependencies of target BamTools
[  1%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamAlignment.cpp.o
[  3%] Building CXX object src/api/CMakeFiles/BamTools.dir/BamMultiReader.cpp.o
...
[100%] Linking CXX executable bamtools
[100%] Built target bamtools_cmd
```

Hope this will solve your problem since it did not happen to me and I might not be able to go over more than this

**Comment by panxiaoguang** [comment]
I think it is indeed the version, but I can't compile successfully bamtools-2.4.0 with my GCC version 7.5.0
